[package]
name = "xtask-lua"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
lux-workspace-hack = { version = "0.1", path = "../lux-workspace-hack" }
toml = "0.8.22"

[features] # For lux-lua distribution
default = []
lua51 = []
lua52 = []
lua53 = []
lua54 = []
luajit = []
