on: 
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
  push:
    branches:
      - master

name: Integration tests (Windows/MSVC)

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: clang-latest

      - name: Install MSVC Compiler Toolchain
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Lua
        uses: luarocks/gh-actions-lua@master
        with:
          luaVersion: "5.1"

      - name: Install neovim
        uses: rhysd/action-setup-vim@v1 # Used by the 'run' integration test
        with:
          neovim: true
          version: v0.11.0

      - name: Install Build+Test dependencies
        run: |
          $env:PATH = "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\bin"
          [Environment]::SetEnvironmentVariable("Path", $env:PATH, "Machine")
          choco install -y --no-progress openssl libgit2 make cmake

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Build
        env:
          OPENSSL_DIR: C:\Program Files\OpenSSL
          OPENSSL_LIB_DIR: C:\Program Files\OpenSSL\lib\VC\x64\MD
        run: cargo build --features vendored-lua

      - name: Run tests
        env:
          OPENSSL_DIR: C:\Program Files\OpenSSL
          OPENSSL_LIB_DIR: C:\Program Files\OpenSSL\lib\VC\x64\MD
          CC_ENABLE_DEBUG_OUTPUT: true
          CFLAGS: "/NOLOGO /MT /O2"
        run: |
          cargo nextest run --test "*" --no-fail-fast --features vendored-lua
